# Generated by Django 6.1 on 2026-08-12 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='coffees/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('EP', 'ESPRESSO'), ('AM', 'AMERICANO'), ('CP', 'CAPPUCCINO'), ('LT', 'LATTE'), ('MC', 'MOCHA')], max_length=2)),
            ],
        ),
    ]
