# Generated by Django 6.1 on 2026-08-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeevariety',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='coffeevariety',
            name='image',
            field=models.ImageField(upload_to='coffee/'),
        ),
    ]
