# Generated by Django 6.1 on 2026-08-16 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_rename_legacy_coffee_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('NEW', 'New request'), ('ACCEPTED', 'Accepted by store'), ('READY', 'Ready for collection'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coffee_variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='coffee.coffeevariety')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='coffee.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
