# Generated by Django 6.1 on 2026-08-16 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_coffeeorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='staff_members',
            field=models.ManyToManyField(blank=True, related_name='managed_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
